[general]
import = [ "~/.config/alacritty/themes/tokyonight.toml" ]
[env]
TERM = "xterm-256color"
[font]
size = 14.0
normal = { family = "FiraCode Nerd Font", style="Retina" }
[window]
option_as_alt = "Both"
decorations_theme_variant = "Dark"
# opacity = 0.95
title = "Алакритя"
dynamic_title = true
resize_increments = true
# padding = { x = 3, y = 3 }
dynamic_padding = true
[mouse]
hide_when_typing = true
[terminal]
shell = {program = "/bin/zsh", args = ["-l", "-c", "tmux attach || tmux"]}

